# Generated by Django 5.1.4 on 2025-01-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourse_link', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='image')),
            ],
        ),
    ]
